<% HappyHour = Rails.application.class.parent_name.underscore %>

development:
  adapter: postgresql
  database: <%= HappyHour%>_development

test:
  adapter: postgresql
  database: <%= HappyHour%>_test

production:
  adapter: postgresql
  database: <%= HappyHour %>_production
